import json

all_products = [
    # CPUs
    {
        'id': 'cpu-1',
        'name': 'AMD Ryzen 7 7800X3D Processor',
        'description': 'The absolute gaming king processor with 3D V-Cache technology. 8 Cores, 16 Threads, 5.0 GHz Max Boost.',
        'price': 4699,
        'oldPrice': 5200,
        'discount': 10,
        'category': 'CPUs',
        'brand': 'AMD',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 12,
        'images': ['PIC PRODUITS/08_124c2ed9-35a7-4eef-8a06-53b081fb3625.jpg'],
        'specs': {'Socket': 'AM5', 'Cores/Threads': '8 / 16', 'TDP': '120W', 'Base Clock': '4.2GHz', 'Boost Clock': '5.0GHz'},
        'tags': ['CPU', 'Processor', 'AMD', 'Gaming', 'AM5'],
        'dateAdded': '2026-07-20T10:00:00Z',
        'salesCount': 45
    },
    {
        'id': 'cpu-2',
        'name': 'Intel Core i7-14700K Desktop Processor',
        'description': '20 Cores (8 P-cores + 12 E-cores) and 28 Threads up to 5.6 GHz. Unmatched multi-tasking and gaming performance.',
        'price': 4899,
        'oldPrice': 5400,
        'discount': 9,
        'category': 'CPUs',
        'brand': 'Intel',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 8,
        'images': ['PIC PRODUITS/1_238bc22f-3ca2-4b52-a194-5462552d11e2.jpg'],
        'specs': {'Socket': 'LGA1700', 'Cores/Threads': '20 / 28', 'TDP': '125W', 'Boost Clock': '5.6GHz'},
        'tags': ['CPU', 'Intel', 'LGA1700', '14th Gen'],
        'dateAdded': '2026-07-22T11:00:00Z',
        'salesCount': 38
    },
    {
        'id': 'cpu-3',
        'name': 'Intel Core i5-13400F Gaming Processor',
        'description': '10 Cores (6 P-cores + 4 E-cores) up to 4.6 GHz. Amazing budget gaming power.',
        'price': 2199,
        'oldPrice': 2499,
        'discount': 12,
        'category': 'CPUs',
        'brand': 'Intel',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 15,
        'images': ['PIC PRODUITS/1_fb85594d-8443-476d-bcef-c6fc2e3ddd20.jpg'],
        'specs': {'Socket': 'LGA1700', 'Cores/Threads': '10 / 16', 'TDP': '65W', 'Boost Clock': '4.6GHz'},
        'tags': ['CPU', 'Intel', 'Budget', 'LGA1700'],
        'dateAdded': '2026-07-15T09:00:00Z',
        'salesCount': 62
    },

    # GPUs
    {
        'id': 'gpu-1',
        'name': 'NVIDIA GeForce RTX 4070 Ti Super 16GB OC',
        'description': 'Powered by Ada Lovelace architecture, DLSS 3, Ray Tracing, 16GB GDDR6X VRAM.',
        'price': 9999,
        'oldPrice': 11200,
        'discount': 11,
        'category': 'GPUs',
        'brand': 'NVIDIA',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 6,
        'images': ['PIC PRODUITS/3_357a6ada-b0fb-491e-a2f6-401d48f3a25e.png'],
        'specs': {'VRAM': '16GB GDDR6X', 'TDP': '285W', 'Interface': 'PCIe 4.0'},
        'tags': ['GPU', 'RTX 4070', 'NVIDIA', 'Ray Tracing'],
        'dateAdded': '2026-07-25T14:00:00Z',
        'salesCount': 29
    },
    {
        'id': 'gpu-2',
        'name': 'NVIDIA GeForce RTX 4060 8GB Gaming OC',
        'description': 'High-FPS 1080p and 1440p gaming with ultra efficiency and DLSS 3 frame generation.',
        'price': 3899,
        'oldPrice': 4300,
        'discount': 9,
        'category': 'GPUs',
        'brand': 'NVIDIA',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 18,
        'images': ['PIC PRODUITS/5_9_fa5d4e16-a769-4a78-9f9d-75ff08f6c47c.jpg'],
        'specs': {'VRAM': '8GB GDDR6', 'TDP': '115W', 'Interface': 'PCIe 4.0'},
        'tags': ['GPU', 'RTX 4060', 'Budget GPU', 'NVIDIA'],
        'dateAdded': '2026-07-18T16:00:00Z',
        'salesCount': 85
    },
    {
        'id': 'gpu-3',
        'name': 'NVIDIA GeForce RTX 4090 24GB Gaming OC',
        'description': 'The ultimate graphic card. 24GB GDDR6X, 4K maxed gaming, AI acceleration.',
        'price': 23999,
        'oldPrice': 25500,
        'discount': 6,
        'category': 'GPUs',
        'brand': 'NVIDIA',
        'platform': 'PC',
        'stockStatus': 'Low Stock',
        'stockQuantity': 2,
        'images': ['PIC PRODUITS/fcb2672aec8421fd55a3927a49c93dcf_ae19ad03-e2ff-4d20-8dd0-a654f3aa1aae.jpg'],
        'specs': {'VRAM': '24GB GDDR6X', 'TDP': '450W', 'Interface': 'PCIe 4.0'},
        'tags': ['GPU', 'RTX 4090', 'Ultimate', '4K Gaming'],
        'dateAdded': '2026-07-10T12:00:00Z',
        'salesCount': 14
    },

    # Motherboards
    {
        'id': 'mb-1',
        'name': 'MSI MAG B650 TOMAHAWK WIFI AM5',
        'description': 'Designed for AMD Ryzen 7000/8000/9000 Series, PCIe 4.0, DDR5, Wi-Fi 6E.',
        'price': 2599,
        'oldPrice': 2899,
        'discount': 10,
        'category': 'Motherboards',
        'brand': 'MSI',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 10,
        'images': ['PIC PRODUITS/f77053d2660675ed74cd58f415dc286d.jpg'],
        'specs': {'Socket': 'AM5', 'RAM Support': 'DDR5', 'Form Factor': 'ATX', 'WiFi': 'Wi-Fi 6E'},
        'tags': ['Motherboard', 'AM5', 'MSI', 'DDR5'],
        'dateAdded': '2026-07-19T10:00:00Z',
        'salesCount': 34
    },
    {
        'id': 'mb-2',
        'name': 'ASUS ROG STRIX B760-F GAMING WIFI LGA1700',
        'description': 'For Intel 12th, 13th & 14th Gen processors, PCIe 5.0, DDR5 support, Aura Sync RGB.',
        'price': 2799,
        'oldPrice': 3100,
        'discount': 10,
        'category': 'Motherboards',
        'brand': 'ASUS',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 7,
        'images': ['PIC PRODUITS/R82HE_C01ULTRA_4a1ee1b8-4ba7-40e8-9e65-832eefa15f8b.jpg'],
        'specs': {'Socket': 'LGA1700', 'RAM Support': 'DDR5', 'Form Factor': 'ATX', 'WiFi': 'Wi-Fi 6E'},
        'tags': ['Motherboard', 'LGA1700', 'ASUS', 'Intel'],
        'dateAdded': '2026-07-21T09:00:00Z',
        'salesCount': 22
    },

    # Mice
    {
        'id': 'mouse-1',
        'name': 'Logitech G PRO X SUPERLIGHT 2 DEX Wireless Mouse',
        'description': 'Ergonomic 60g ultra-lightweight esports gaming mouse with HERO 2 sensor.',
        'price': 1799,
        'oldPrice': 1999,
        'discount': 10,
        'category': 'Mice',
        'brand': 'Logitech',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 22,
        'images': ['PIC PRODUITS/pro-x-superlight-2-dex-mouse-profile-left-angle-black-gallery-4-2-award.png'],
        'specs': {'Sensor': 'HERO 2 (32K DPI)', 'Weight': '60g', 'Battery': '95h'},
        'tags': ['Souris', 'Mouse', 'Logitech', 'Wireless'],
        'dateAdded': '2026-07-24T10:00:00Z',
        'salesCount': 110
    },
    {
        'id': 'mouse-2',
        'name': 'Logitech G PRO X SUPERLIGHT 2 SE Red Magenta',
        'description': 'Professional wireless esports mouse in stunning SE Red colorway.',
        'price': 1849,
        'oldPrice': 2099,
        'discount': 11,
        'category': 'Mice',
        'brand': 'Logitech',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 14,
        'images': ['PIC PRODUITS/pro-x-superlight-2-se-red-profile-left-angle-gallery-4.png'],
        'specs': {'Sensor': 'HERO 2', 'Weight': '60g', 'Color': 'Red'},
        'tags': ['Souris', 'Mouse', 'Red', 'Logitech'],
        'dateAdded': '2026-07-25T11:00:00Z',
        'salesCount': 42
    },
    {
        'id': 'mouse-3',
        'name': 'Logitech G PRO X SUPERLIGHT 2 White',
        'description': 'Lightweight white esports gaming mouse with LIGHTSPEED wireless technology.',
        'price': 1799,
        'oldPrice': 1999,
        'discount': 10,
        'category': 'Mice',
        'brand': 'Logitech',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 19,
        'images': ['PIC PRODUITS/pro-x-superlight-2c-mouse-profile-left-angle-offwhite-gallery-4-2-award.png'],
        'specs': {'Sensor': 'HERO 2', 'Weight': '60g', 'Color': 'White'},
        'tags': ['Souris', 'Mouse', 'White', 'Logitech'],
        'dateAdded': '2026-07-23T09:00:00Z',
        'salesCount': 78
    },
    {
        'id': 'mouse-4',
        'name': 'Logitech G502 HERO High Performance Gaming Mouse',
        'description': '11 programmable buttons, HERO 25K sensor, adjustable weights RGB gaming mouse.',
        'price': 599,
        'oldPrice': 749,
        'discount': 20,
        'category': 'Mice',
        'brand': 'Logitech',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 35,
        'images': ['PIC PRODUITS/g502-hero-mouse-profile-left-angle-gallery-2.png'],
        'specs': {'Sensor': 'HERO 25K', 'Buttons': '11', 'Weight': '121g'},
        'tags': ['Souris', 'Mouse', 'Logitech', 'G502'],
        'dateAdded': '2026-07-12T08:00:00Z',
        'salesCount': 210
    },
    {
        'id': 'mouse-5',
        'name': 'Logitech G502 X LIGHTSPEED Wireless Mouse White',
        'description': 'Redesigned G502 with LIGHTFORCE hybrid optical-mechanical switches.',
        'price': 1499,
        'oldPrice': 1699,
        'discount': 11,
        'category': 'Mice',
        'brand': 'Logitech',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 16,
        'images': ['PIC PRODUITS/g502x-lightspeed-gallery-4-white.png'],
        'specs': {'Switches': 'LIGHTFORCE Hybrid', 'Weight': '102g', 'Color': 'White'},
        'tags': ['Souris', 'Mouse', 'Logitech', 'Wireless'],
        'dateAdded': '2026-07-21T15:00:00Z',
        'salesCount': 64
    },
    {
        'id': 'mouse-6',
        'name': 'Logitech G403 HERO Wired Gaming Mouse',
        'description': 'Ergonomic shape, rubber side grips, HERO 25K sensor, customizable RGB.',
        'price': 499,
        'oldPrice': 599,
        'discount': 16,
        'category': 'Mice',
        'brand': 'Logitech',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 20,
        'images': ['PIC PRODUITS/g403-wired-gallery-2-nb.png'],
        'specs': {'Sensor': 'HERO 25K', 'Weight': '87g', 'RGB': 'LIGHTSYNC'},
        'tags': ['Souris', 'Mouse', 'Logitech', 'G403'],
        'dateAdded': '2026-07-11T10:00:00Z',
        'salesCount': 50
    },
    {
        'id': 'pad-1',
        'name': 'Logitech G740 Large Cloth Gaming Mouse Pad',
        'description': '5mm thick heavy cloth mouse pad tuned for low DPI gaming and precision movement.',
        'price': 299,
        'oldPrice': 349,
        'discount': 14,
        'category': 'Mice',
        'brand': 'Logitech',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 40,
        'images': ['PIC PRODUITS/g740-gallery-2.png'],
        'specs': {'Size': '400 x 460 mm', 'Thickness': '5mm', 'Material': 'Cloth'},
        'tags': ['Tapis', 'Mousepad', 'Logitech'],
        'dateAdded': '2026-07-16T12:00:00Z',
        'salesCount': 95
    },

    # Headsets
    {
        'id': 'headset-1',
        'name': 'Logitech G PRO X 2 LIGHTSPEED Wireless Gaming Headset',
        'description': 'Pro-grade gaming headset featuring 50mm Graphene drivers, DTS Headphone:X 2.0 surround sound.',
        'price': 2499,
        'oldPrice': 2799,
        'discount': 11,
        'category': 'Headsets',
        'brand': 'Logitech',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 14,
        'images': ['PIC PRODUITS/pro-headset-gallery-2.png'],
        'specs': {'Drivers': '50mm Graphene', 'Battery': '50 Hours', 'Connectivity': 'LIGHTSPEED Wireless'},
        'tags': ['Casque', 'Headset', 'Logitech', 'Wireless'],
        'dateAdded': '2026-07-22T14:00:00Z',
        'salesCount': 48
    },
    {
        'id': 'headset-2',
        'name': 'Logitech G PRO X SE Special Edition Gaming Headset',
        'description': 'Advanced PRO X wired gaming headset with detachable Blue VO!CE mic.',
        'price': 1299,
        'oldPrice': 1499,
        'discount': 13,
        'category': 'Headsets',
        'brand': 'Logitech',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 18,
        'images': ['PIC PRODUITS/pro-x-se-front-angle-gallery-2.png'],
        'specs': {'Drivers': '50mm PRO-G', 'Mic': 'Blue VO!CE', 'Audio': '7.1 Surround'},
        'tags': ['Casque', 'Headset', 'Logitech', 'Pro X'],
        'dateAdded': '2026-07-19T13:00:00Z',
        'salesCount': 72
    },
    {
        'id': 'headset-3',
        'name': 'Logitech G733 LIGHTSPEED Wireless RGB Headset - Lilac',
        'description': 'Ultra-lightweight 278g wireless gaming headset with customizable LIGHTSYNC RGB.',
        'price': 1499,
        'oldPrice': 1699,
        'discount': 12,
        'category': 'Headsets',
        'brand': 'Logitech',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 11,
        'images': ['PIC PRODUITS/g733-lilac-gallery-2.png'],
        'specs': {'Weight': '278g', 'Battery': '29 Hours', 'RGB': 'LIGHTSYNC'},
        'tags': ['Casque', 'Headset', 'Logitech', 'RGB', 'Lilac'],
        'dateAdded': '2026-07-20T11:00:00Z',
        'salesCount': 37
    },
    {
        'id': 'headset-4',
        'name': 'HyperX Cloud III Wireless Gaming Headset',
        'description': 'Legendary Cloud comfort with up to 120 hours of battery life and 53mm angled drivers.',
        'price': 1699,
        'oldPrice': 1899,
        'discount': 10,
        'category': 'Headsets',
        'brand': 'HyperX',
        'platform': 'Universal',
        'stockStatus': 'In Stock',
        'stockQuantity': 15,
        'images': ['PIC PRODUITS/hv3xhs_xboxps_homepage2x_3840x1400.webp'],
        'specs': {'Battery': '120 Hours', 'Drivers': '53mm Angled', 'Audio': 'DTS Headphone:X'},
        'tags': ['Casque', 'Headset', 'HyperX', 'Cloud III'],
        'dateAdded': '2026-07-17T16:00:00Z',
        'salesCount': 89
    },
    {
        'id': 'headset-5',
        'name': 'Logitech G935 Wireless 7.1 Surround RGB Headset',
        'description': '50mm Pro-G drivers, DTS Headphone:X 2.0 surround sound, LIGHTSYNC RGB lighting.',
        'price': 1899,
        'oldPrice': 2199,
        'discount': 13,
        'category': 'Headsets',
        'brand': 'Logitech',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 9,
        'images': ['PIC PRODUITS/g935-3qtr-back-left-angle-gallery-3.png'],
        'specs': {'Drivers': '50mm Pro-G', 'Surround': 'DTS 2.0', 'RGB': 'LIGHTSYNC'},
        'tags': ['Casque', 'Headset', 'Logitech', 'G935'],
        'dateAdded': '2026-07-14T14:00:00Z',
        'salesCount': 41
    },
    {
        'id': 'headset-6',
        'name': 'Logitech G535 LIGHTSPEED Wireless Gaming Headset',
        'description': 'Lightweight 236g wireless headset with reversible headband strap and flip-to-mute mic.',
        'price': 1199,
        'oldPrice': 1399,
        'discount': 14,
        'category': 'Headsets',
        'brand': 'Logitech',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 17,
        'images': ['PIC PRODUITS/g535-wireless-gallery-2.png'],
        'specs': {'Weight': '236g', 'Battery': '33 Hours', 'Drivers': '40mm'},
        'tags': ['Casque', 'Headset', 'Logitech', 'G535'],
        'dateAdded': '2026-07-18T10:00:00Z',
        'salesCount': 63
    },
    {
        'id': 'headset-7',
        'name': 'Logitech G432 7.1 Surround Sound Gaming Headset',
        'description': '50mm drivers, 6mm flip-to-mute mic, multi-platform compatibility.',
        'price': 699,
        'oldPrice': 849,
        'discount': 17,
        'category': 'Headsets',
        'brand': 'Logitech',
        'platform': 'Universal',
        'stockStatus': 'In Stock',
        'stockQuantity': 25,
        'images': ['PIC PRODUITS/g432-3qtr-back-right-angle-gallery-3.png'],
        'specs': {'Drivers': '50mm', 'Mic': '6mm Flip-to-mute', 'Surround': '7.1 DTS'},
        'tags': ['Casque', 'Headset', 'Logitech', 'G432'],
        'dateAdded': '2026-07-11T11:00:00Z',
        'salesCount': 105
    },
    {
        'id': 'headset-8',
        'name': 'Logitech G321 LIGHTSPEED Wireless Gaming Headset',
        'description': 'Ultra comfortable lightweight wireless headset with low-latency LIGHTSPEED wireless.',
        'price': 899,
        'oldPrice': 1099,
        'discount': 18,
        'category': 'Headsets',
        'brand': 'Logitech',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 12,
        'images': ['PIC PRODUITS/g321-lightspeed-3qtr-high-front-right-angle-black-gallery-3.png'],
        'specs': {'Connectivity': 'LIGHTSPEED Wireless', 'Battery': '24h'},
        'tags': ['Casque', 'Headset', 'Logitech', 'G321'],
        'dateAdded': '2026-07-13T15:00:00Z',
        'salesCount': 33
    },

    # Microphones & Streaming Lights
    {
        'id': 'mic-1',
        'name': 'Logitech Blue Yeti Professional USB Microphone - Blackout',
        'description': 'Tri-capsule array USB mic for gaming, streaming, podcasting, and YouTube content creation.',
        'price': 1399,
        'oldPrice': 1599,
        'discount': 12,
        'category': 'Microphones',
        'brand': 'Logitech',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 16,
        'images': ['PIC PRODUITS/yeti-3qtr-left-angle-blackout-gallery-4.png'],
        'specs': {'Capsules': '3 Condenser Capsules', 'Patterns': '4 Pickup Patterns', 'Sample Rate': '48kHz'},
        'tags': ['Microphone', 'Yeti', 'Logitech', 'Streaming'],
        'dateAdded': '2026-07-15T10:00:00Z',
        'salesCount': 54
    },
    {
        'id': 'mic-2',
        'name': 'Logitech Yeti GX Dynamic RGB Gaming Microphone White',
        'description': 'Broadcast-style dynamic USB microphone with custom LIGHTSYNC RGB and Smart Audio Lock.',
        'price': 1799,
        'oldPrice': 1999,
        'discount': 10,
        'category': 'Microphones',
        'brand': 'Logitech',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 10,
        'images': ['PIC PRODUITS/yeti-gx-3qtr-front-angle-white-gallery-4.png'],
        'specs': {'Capsule': 'Dynamic Capsule', 'Pattern': 'Supercardioid', 'RGB': 'LIGHTSYNC'},
        'tags': ['Microphone', 'Yeti GX', 'Logitech', 'White'],
        'dateAdded': '2026-07-22T09:00:00Z',
        'salesCount': 28
    },
    {
        'id': 'mic-3',
        'name': 'Logitech Blue Yeti Nano Premium USB Microphone',
        'description': 'Compact USB condenser microphone with studio-quality 24-bit sound for podcasting.',
        'price': 999,
        'oldPrice': 1199,
        'discount': 16,
        'category': 'Microphones',
        'brand': 'Logitech',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 14,
        'images': ['PIC PRODUITS/yeti-nano-3qtr-front-left-angle-black-gallery-3.png'],
        'specs': {'Sample Rate': '24-bit / 48kHz', 'Patterns': 'Cardioid, Omnidirectional'},
        'tags': ['Microphone', 'Yeti Nano', 'Logitech'],
        'dateAdded': '2026-07-13T12:00:00Z',
        'salesCount': 49
    },
    {
        'id': 'mic-4',
        'name': 'Logitech Yeti Studio Broadcast Microphone White',
        'description': 'All-in-one streaming package with pro broadcast vocal mic and custom EQ presets.',
        'price': 1999,
        'oldPrice': 2299,
        'discount': 13,
        'category': 'Microphones',
        'brand': 'Logitech',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 8,
        'images': ['PIC PRODUITS/yeti-studio-microphone-white-gallery-2.png'],
        'specs': {'Type': 'Broadcast Condenser', 'Color': 'White'},
        'tags': ['Microphone', 'Yeti Studio', 'Logitech'],
        'dateAdded': '2026-07-21T11:00:00Z',
        'salesCount': 22
    },
    {
        'id': 'boom-1',
        'name': 'Blue Compass Premium Broadcast Boom Arm',
        'description': 'Enclosed aluminum construction with internal springs and hidden cable management channel.',
        'price': 1199,
        'oldPrice': 1399,
        'discount': 14,
        'category': 'Microphones',
        'brand': 'Logitech',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 12,
        'images': ['PIC PRODUITS/compass-g-3qtr-angle-gallery-4.png'],
        'specs': {'Rotation': '360 Degrees', 'Reach': '32 inches', 'Max Weight': '2.4 lbs'},
        'tags': ['Bras', 'Boom Arm', 'Compass', 'Logitech'],
        'dateAdded': '2026-07-16T14:00:00Z',
        'salesCount': 31
    },
    {
        'id': 'light-1',
        'name': 'Logitech Litra Beam Premium LED Streaming Light',
        'description': 'Key light featuring TrueSoft technology, adjustable height, tilt, and brightness presets.',
        'price': 1199,
        'oldPrice': 1399,
        'discount': 14,
        'category': 'Microphones',
        'brand': 'Logitech',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 15,
        'images': ['PIC PRODUITS/litra-beam-gallery-1.png'],
        'specs': {'Technology': 'TrueSoft LED', 'Color Temp': '2700K - 6500K'},
        'tags': ['Eclairage', 'Litra Beam', 'Logitech'],
        'dateAdded': '2026-07-17T11:00:00Z',
        'salesCount': 39
    },
    {
        'id': 'light-2',
        'name': 'Logitech Litra Beam LX Dual-Sided RGB Light',
        'description': 'Dual-sided streaming light with key lighting on one side and customizable RGB animation on back.',
        'price': 1499,
        'oldPrice': 1699,
        'discount': 11,
        'category': 'Microphones',
        'brand': 'Logitech',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 10,
        'images': ['PIC PRODUITS/litra-beam-gallery-6.png'],
        'specs': {'Features': 'Dual Sided LED + RGB', 'Control': 'G HUB App'},
        'tags': ['Eclairage', 'Litra LX', 'RGB', 'Logitech'],
        'dateAdded': '2026-07-23T13:00:00Z',
        'salesCount': 26
    },

    # Webcams
    {
        'id': 'cam-1',
        'name': 'Logitech C920s HD Pro Webcam with Privacy Shutter',
        'description': 'Full HD 1080p video calling and recording at 30fps with stereo audio and autofocus.',
        'price': 899,
        'oldPrice': 1099,
        'discount': 18,
        'category': 'Microphones',
        'brand': 'Logitech',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 25,
        'images': ['PIC PRODUITS/c920s-gallery-2.png'],
        'specs': {'Resolution': '1080p / 30fps', 'Lens': 'Glass', 'Focus': 'Autofocus'},
        'tags': ['Webcam', 'C920s', 'Logitech'],
        'dateAdded': '2026-07-10T09:00:00Z',
        'salesCount': 120
    },
    {
        'id': 'cam-2',
        'name': 'Logitech C922 Pro Stream Webcam with Tripod',
        'description': 'Designed for serious streamers with hyper-fast 60fps at 720p or 30fps at 1080p.',
        'price': 1099,
        'oldPrice': 1299,
        'discount': 15,
        'category': 'Microphones',
        'brand': 'Logitech',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 18,
        'images': ['PIC PRODUITS/c922-gallery-2.png'],
        'specs': {'Resolution': '1080p/30fps, 720p/60fps', 'Include': 'Mini Tripod'},
        'tags': ['Webcam', 'C922', 'Logitech', 'Streaming'],
        'dateAdded': '2026-07-12T14:00:00Z',
        'salesCount': 98
    },
    {
        'id': 'cam-3',
        'name': 'Logitech MX Brio Ultra HD 4K Webcam',
        'description': '4K resolution streaming webcam with enlarged STARVIS sensor and AI image enhancement.',
        'price': 2299,
        'oldPrice': 2599,
        'discount': 11,
        'category': 'Microphones',
        'brand': 'Logitech',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 9,
        'images': ['PIC PRODUITS/mx-brio-3qtr-front-right-pale-gray.png'],
        'specs': {'Resolution': '4K / 30fps, 1080p / 60fps', 'Sensor': 'Sony STARVIS'},
        'tags': ['Webcam', 'MX Brio', '4K', 'Logitech'],
        'dateAdded': '2026-07-24T16:00:00Z',
        'salesCount': 19
    },

    # Controllers & Wheels
    {
        'id': 'wheel-1',
        'name': 'Logitech G29 Driving Force Racing Wheel & Pedals',
        'description': 'Dual-motor force feedback racing wheel for PlayStation 5, PS4 and PC with helical gearing.',
        'price': 3499,
        'oldPrice': 3899,
        'discount': 10,
        'category': 'Controllers',
        'brand': 'Logitech',
        'platform': 'PlayStation',
        'stockStatus': 'In Stock',
        'stockQuantity': 8,
        'images': ['PIC PRODUITS/g29-playstation-3qtr-angle-gallery-4.png'],
        'specs': {'Rotation': '900 Degrees', 'Feedback': 'Dual-Motor Force Feedback'},
        'tags': ['Volant', 'Racing Wheel', 'Logitech', 'PS5', 'PC'],
        'dateAdded': '2026-07-18T13:00:00Z',
        'salesCount': 26
    },
    {
        'id': 'wheel-2',
        'name': 'Logitech G923 TRUEFORCE Racing Wheel for PS5/PC',
        'description': 'Next-gen TRUEFORCE force feedback system dialing directly into game physics engine.',
        'price': 4299,
        'oldPrice': 4799,
        'discount': 10,
        'category': 'Controllers',
        'brand': 'Logitech',
        'platform': 'PlayStation',
        'stockStatus': 'In Stock',
        'stockQuantity': 6,
        'images': ['PIC PRODUITS/g923-ps4-badge-gallery-new-1.png'],
        'specs': {'Technology': 'TRUEFORCE', 'Pedals': 'Progressive Brake Pedal'},
        'tags': ['Volant', 'G923', 'TRUEFORCE', 'Logitech'],
        'dateAdded': '2026-07-20T14:00:00Z',
        'salesCount': 34
    },
    {
        'id': 'wheel-3',
        'name': 'Logitech G PRO RS Round Track Steering Wheel',
        'description': 'Direct drive professional track racing rim crafted with premium leather and quick release system.',
        'price': 3999,
        'oldPrice': 4499,
        'discount': 11,
        'category': 'Controllers',
        'brand': 'Logitech',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 5,
        'images': ['PIC PRODUITS/rs-round-wheel-3qtr-front-right-angle-gallery-3.png'],
        'specs': {'Rim': 'Round Leather Track Rim', 'Release': 'Quick Release System'},
        'tags': ['Volant', 'RS Wheel', 'Logitech', 'Pro Track'],
        'dateAdded': '2026-07-25T10:00:00Z',
        'salesCount': 12
    },
    {
        'id': 'shifter-1',
        'name': 'Logitech Driving Force Shifter for G29 / G920',
        'description': 'Six-speed H-pattern gear shifter with push-down reverse gear for racing wheels.',
        'price': 699,
        'oldPrice': 799,
        'discount': 12,
        'category': 'Controllers',
        'brand': 'Logitech',
        'platform': 'Universal',
        'stockStatus': 'In Stock',
        'stockQuantity': 22,
        'images': ['PIC PRODUITS/shifter-gallery-2.png'],
        'specs': {'Gears': '6-Speed H-Pattern', 'Mounting': 'Built-in Clamps'},
        'tags': ['Levier', 'Shifter', 'Logitech', 'G29'],
        'dateAdded': '2026-07-15T15:00:00Z',
        'salesCount': 85
    },
    {
        'id': 'shifter-2',
        'name': 'Logitech G PRO RS Shifter & Handbrake Dual System',
        'description': 'Sequential shifter and analog handbrake combined in one steel pro sim racing unit.',
        'price': 1899,
        'oldPrice': 2199,
        'discount': 13,
        'category': 'Controllers',
        'brand': 'Logitech',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 7,
        'images': ['PIC PRODUITS/rs-shifter-handbrake-gallery2.png'],
        'specs': {'Modes': 'Sequential Shifter & Handbrake', 'Material': 'Steel'},
        'tags': ['Shifter', 'Handbrake', 'RS', 'Logitech'],
        'dateAdded': '2026-07-24T12:00:00Z',
        'salesCount': 17
    },
    {
        'id': 'pad-ctrl-1',
        'name': 'Logitech F310 Gamepad Controller',
        'description': 'Familiar console-style layout PC controller with XInput/DirectInput modes.',
        'price': 299,
        'oldPrice': 349,
        'discount': 14,
        'category': 'Controllers',
        'brand': 'Logitech',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 30,
        'images': ['PIC PRODUITS/f310-gallery-2.png'],
        'specs': {'Modes': 'XInput & DirectInput', 'Cable': '1.8m'},
        'tags': ['Manette', 'F310', 'Logitech'],
        'dateAdded': '2026-07-08T10:00:00Z',
        'salesCount': 140
    },
    {
        'id': 'pad-ctrl-2',
        'name': 'Logitech F710 Wireless Gamepad Controller',
        'description': '2.4 GHz wireless gamepad with dual vibration feedback motors.',
        'price': 499,
        'oldPrice': 599,
        'discount': 16,
        'category': 'Controllers',
        'brand': 'Logitech',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 20,
        'images': ['PIC PRODUITS/f710-gallery-2.png'],
        'specs': {'Connectivity': '2.4 GHz Wireless', 'Feedback': 'Dual Vibration Motors'},
        'tags': ['Manette', 'F710', 'Logitech', 'Wireless'],
        'dateAdded': '2026-07-09T11:00:00Z',
        'salesCount': 96
    },
    {
        'id': 'ctrl-razer-1',
        'name': 'Razer Wolverine V3 Pro Wireless Esports Controller',
        'description': 'Official wireless tournament controller with Hall Effect thumbsticks and 4 rear paddles.',
        'price': 2299,
        'oldPrice': 2500,
        'discount': 8,
        'category': 'Controllers',
        'brand': 'Razer',
        'platform': 'Xbox',
        'stockStatus': 'In Stock',
        'stockQuantity': 10,
        'images': ['PIC PRODUITS/wolverine-v3-pro-500x500.png'],
        'specs': {'Thumbsticks': 'Hall Effect Anti-Drift', 'Paddles': '4 Back Buttons'},
        'tags': ['Manette', 'Wolverine', 'Razer', 'Xbox'],
        'dateAdded': '2026-07-23T11:00:00Z',
        'salesCount': 19
    },
    {
        'id': 'ctrl-razer-2',
        'name': 'Razer Wolverine V3 Pro 8K PC Black Controller',
        'description': '8000Hz polling rate hyper-polling wireless controller for extreme low latency gaming.',
        'price': 2499,
        'oldPrice': 2799,
        'discount': 10,
        'category': 'Controllers',
        'brand': 'Razer',
        'platform': 'PC',
        'stockStatus': 'In Stock',
        'stockQuantity': 8,
        'images': ['PIC PRODUITS/wolverine-v3-pro-8k-pc-black-500x500.png'],
        'specs': {'Polling Rate': '8000Hz (8K)', 'Color': 'Black'},
        'tags': ['Manette', 'Razer 8K', 'PC'],
        'dateAdded': '2026-07-24T14:00:00Z',
        'salesCount': 15
    },
    {
        'id': 'ctrl-razer-3',
        'name': 'Razer Wolverine V3 Tournament Edition Wired Controller',
        'description': 'Wired esports controller engineered with mecha-tactile action buttons.',
        'price': 1499,
        'oldPrice': 1699,
        'discount': 11,
        'category': 'Controllers',
        'brand': 'Razer',
        'platform': 'Xbox',
        'stockStatus': 'In Stock',
        'stockQuantity': 14,
        'images': ['PIC PRODUITS/wolverine-v3-te-8k-pc-black-500x500.png'],
        'specs': {'Buttons': 'Mecha-Tactile', 'Paddles': '4 Rear Buttons'},
        'tags': ['Manette', 'Razer TE', 'Xbox'],
        'dateAdded': '2026-07-21T09:00:00Z',
        'salesCount': 27
    },
    {
        'id': 'ctrl-razer-4',
        'name': 'Razer Wolverine V3 TE White Controller',
        'description': 'Special Edition White wired tournament controller with instant trigger locks.',
        'price': 1549,
        'oldPrice': 1749,
        'discount': 11,
        'category': 'Controllers',
        'brand': 'Razer',
        'platform': 'Xbox',
        'stockStatus': 'In Stock',
        'stockQuantity': 11,
        'images': ['PIC PRODUITS/wolverine-v3-te-white-500x500.png'],
        'specs': {'Color': 'Mercury White', 'Triggers': 'Hair Trigger Locks'},
        'tags': ['Manette', 'Razer White', 'Xbox'],
        'dateAdded': '2026-07-22T10:00:00Z',
        'salesCount': 21
    },
    {
        'id': 'ps5-stand-1',
        'name': 'DualSense Quick Charging Stand for PS5 White',
        'description': 'Click-in dock charges up to two DualSense wireless controllers simultaneously without USB ports.',
        'price': 399,
        'oldPrice': 499,
        'discount': 20,
        'category': 'Controllers',
        'brand': 'Sony',
        'platform': 'PlayStation',
        'stockStatus': 'In Stock',
        'stockQuantity': 30,
        'images': ['PIC PRODUITS/quick-charging-stand-for-ps5-white-500x500.png'],
        'specs': {'Capacity': '2 Controllers', 'Color': 'White'},
        'tags': ['Chargeur', 'PS5', 'DualSense', 'Sony'],
        'dateAdded': '2026-07-16T08:00:00Z',
        'salesCount': 112
    },

    # Chairs
    {
        'id': 'chair-1',
        'name': 'Razer Iskur V2 Ergonomic Gaming Chair Black/Green',
        'description': 'Ergonomic gaming chair featuring adaptive lumbar support system and high-density foam cushions.',
        'price': 5499,
        'oldPrice': 5999,
        'discount': 8,
        'category': 'Gaming Chairs',
        'brand': 'Razer',
        'platform': 'Universal',
        'stockStatus': 'In Stock',
        'stockQuantity': 5,
        'images': ['PIC PRODUITS/iskur-v2-newgen-blackgreen-500x500.png'],
        'specs': {'Lumbar': 'Adaptive Lumbar Support', 'Material': 'Synthetic Leather'},
        'tags': ['Chaise', 'Gaming Chair', 'Razer', 'Iskur'],
        'dateAdded': '2026-07-14T09:00:00Z',
        'salesCount': 15
    },
    {
        'id': 'chair-2',
        'name': 'Razer Enki Black Premium Gaming Chair',
        'description': 'Designed for all-day comfort with 110-degree extended shoulder arches and built-in lumbar arch.',
        'price': 4899,
        'oldPrice': 5399,
        'discount': 9,
        'category': 'Gaming Chairs',
        'brand': 'Razer',
        'platform': 'Universal',
        'stockStatus': 'In Stock',
        'stockQuantity': 4,
        'images': ['PIC PRODUITS/enki-black-500x500.png'],
        'specs': {'Recline': '152 Degrees', 'Color': 'Black'},
        'tags': ['Chaise', 'Enki', 'Razer'],
        'dateAdded': '2026-07-19T10:00:00Z',
        'salesCount': 11
    },
    {
        'id': 'chair-3',
        'name': 'Razer Fujin Pro Breathable Mesh Gaming Chair',
        'description': 'Ultra-breathable mesh gaming chair with aluminum alloy frame and 3D armrests.',
        'price': 6999,
        'oldPrice': 7500,
        'discount': 6,
        'category': 'Gaming Chairs',
        'brand': 'Razer',
        'platform': 'Universal',
        'stockStatus': 'In Stock',
        'stockQuantity': 3,
        'images': ['PIC PRODUITS/fujin-500x500.png'],
        'specs': {'Frame': 'Aluminum Alloy', 'Material': 'Breathable Mesh'},
        'tags': ['Chaise', 'Fujin', 'Razer'],
        'dateAdded': '2026-07-23T15:00:00Z',
        'salesCount': 7
    }
]

with open('products.json', 'w', encoding='utf-8') as f:
    json.dump(all_products, f, indent=2, ensure_ascii=False)

print(f'Successfully cataloged all {len(all_products)} products into products.json!')
